wandb_version: 1

batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 2
lr:
  desc: null
  value: 0.08437829068130401
_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689421771.700502
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      - 37
      4: 3.7.16
      5: 0.15.3
      8:
      - 5
      10:
      - 2
