program: run_train.py
name: swipe-batches
project: Batches
method: random #bayes
run_cap: 2
metric:
  name: eval_loss
  goal: minimize
parameters:
  epochs: 
    value: 2
  batch_size: 
    #values: [2, 4, 8, 16, 32, 64, 128, 256, 512]
    values: [512]
  lr:
    values: [0.01]
  dataset:
    values: ['adult_dataset']
  seed:
    value: 42
