program: run_train.py
<<<<<<< HEAD
name: swipe-batches-cancer-3
project: Batches_cancer_3
=======
name: swipe-batches-cancer
project: Batches_cancer
>>>>>>> origin/main
method: grid
run_cap: 1022
metric:
  name: val_acc
  goal: maximize
parameters:
  epochs: 
    value: 90
  batch_size: 
    min: 2
    max: 1024
  lr:
    values: [0.01]
<<<<<<< HEAD
  lr_decay:
    value: False
  dataset:
    value: 'cancer_risk_2'
=======
  dataset:
    value: 'cancer_risk'
>>>>>>> origin/main
  seed:
    value: 42
EarlyStopping:
  patience: 5
  min_delta: 0
  decreasing: False

