program: run_train.py
name: swipe-batches-1022-4
project: Batches_1024_bank
method: grid
run_cap: 1022
metric:
  name: val_acc
  goal: maximize
model: nn.Sequential(
            nn.Linear(input_size, hidden_sizes[0]),
            nn.ReLU(),
            nn.Linear(hidden_sizes[0], hidden_sizes[1]),
            nn.ReLU(),
            nn.Linear(hidden_sizes[1], output_size),
            nn.Sigmoid(),
        )
parameters:
  epochs: 
    value: 90
  batch_size: 
    min: 2
    max: 1024
  lr:
    values: [0.01]
  dataset:
    value: 'bank_marketing'
  seed:
    value: 42
EarlyStopping:
  patience: 5
  min_delta: 0
  decreasing: False

