program: run_train.py
name: swipe-batches-sgd
project: Batches_bank_sgd
method: grid
run_cap: 1022
metric:
  name: val_acc
  goal: maximize
parameters:
  epochs: 
    value: 90
  batch_size: 
    min: 2
    max: 1024
  lr:
    values: [0.01]
  lr_decay:
    value: False
  dataset:
    value: 'bank_marketing'
  seed:
    value: 42
EarlyStopping:
  patience: 5
  min_delta: 0
  decreasing: False

