program: run_train.py
name: swipe-batches
project: Batches
method: random #bayes
run_cap: 9
metric:
  name: val_acc
  goal: maximize
model: nn.Sequential(
            nn.Linear(input_size, hidden_sizes[0]),
            nn.ReLU(),
            nn.Linear(hidden_sizes[0], hidden_sizes[1]),
            nn.ReLU(),
            nn.Linear(hidden_sizes[1], output_size),
            nn.Sigmoid(),
        )
parameters:
  epochs: 
    value: 50
  batch_size: 
    values: [2, 4, 8, 16, 32, 64, 128, 256, 512]
  lr:
    values: [0.01]
  dataset:
    values: ['adult_dataset']
  seed:
    value: 42
