program: run_train.py
name: swipe-name-lr
project: LearninRate
method: random #bayes
run_cap: 1000
metric:
  name: val_acc
  goal: maximize
model: nn.Sequential(
            nn.Linear(input_size, hidden_sizes[0]),
            nn.ReLU(),
            nn.Linear(hidden_sizes[0], hidden_sizes[1]),
            nn.ReLU(),
            nn.Linear(hidden_sizes[1], output_size),
            nn.Sigmoid(),
        )
parameters:
  epochs: 
    value: 90
  batch_size: 
    values: [256]
  lr:
    min: 0.00001
    max: 0.1
  dataset:
    value: 'adult_dataset'
  seed:
    value: 42
EarlyStopping:
  patience: 5
  min_delta: 0
  decreasing: False
