program: run_train.py
name: swipe-name-lr-attrition
project: LearninRate_attrition
method: random
run_cap: 1000
metric:
  name: val_acc
  goal: maximize
parameters:
  epochs: 
    value: 90
  batch_size: 
    values: [128]
  lr:
    min: 0.00001
    max: 0.1
  dataset:
    value: 'ibm_attrition'
  seed:
    value: 42
EarlyStopping:
  patience: 5
  min_delta: 0
  decreasing: False
