program: run_train.py
name: swipe-name-lr-bank-mitigation
project: LearninRate_bank-mitigation
method: random
run_cap: 1000
metric:
  name: val_acc
  goal: maximize
parameters:
  epochs: 
    value: 90
  batch_size: 
    values: [256]
  lr:
    min: 0.00001
    max: 0.1
  lr_decay:
    value: True
  dataset:
    value: 'bank_marketing'
  seed:
    value: 42
EarlyStopping:
  patience: 5
  min_delta: 0
  decreasing: False
