program: run_train.py
name: swipe-name-test
project: test-yaml-lr-batch-4
method: random #bayes
run_cap: 6
metric:
  name: eval_loss
  goal: minimize
parameters:
  epochs: 
    value: 2
  batch_size: 
    values: [8, 16, 32, 64, 128, 256]
  lr:
    values: [0.01, 0.001, 0.0001, 0.0003, 0.00003]
  dataset:
    values: ['adult_dataset']
  seed:
    value: 42
