program: run_train.py
name: swipe-name-lr-churn-bs
project: LearninRate_churn_bs
method: random
run_cap: 1000
metric:
  name: val_acc
  goal: maximize
parameters:
  epochs: 
    value: 90
  batch_size: 
    values: [998]
  lr:
    min: 0.00001
    max: 0.1
  lr_decay:
    value: False
  dataset:
    value: 'churn_dataset'
  seed:
    value: 42
EarlyStopping:
  patience: 5
  min_delta: 0
  decreasing: False
