program: run_train.py
name: swipe-seed
project: Random-seed
method: random #bayes grid
run_cap: 1000
metric:
  name: eval_loss
  goal: minimize
parameters:
  epochs: 
    value: 50
  batch_size: 
    values: [64]
  lr:
    values: [0.001]
  dataset:
    values: ['adult_dataset']
  seed:
    min: 1
    max: 3000000000
