program: run_train.py
name: swipe-seed-bank-mitigation
project: Random_seed_bank-mitigation
method: random
run_cap: 1000
metric:
  name: val_acc
  goal: maximize
parameters:
  epochs: 
    value: 90
  batch_size: 
    values: [256]
  lr:
    values: [0.01]
  lr_decay:
    value: True
  dataset:
    value: 'bank_marketing'
  seed:
    min: 1
    max: 3000000000

EarlyStopping:
  patience: 5
  min_delta: 0
  decreasing: False