program: run_train.py
name: swipe-seed-rs-attrition
project: Random_seed_attrition
<<<<<<< HEAD
method: random
=======
method: random #bayes grid
>>>>>>> origin/main
run_cap: 1000
metric:
  name: val_acc
  goal: maximize
parameters:
  epochs: 
    value: 90
  batch_size: 
    values: [128]
  lr:
    values: [0.01]
  dataset:
    value: 'ibm_attrition'
  seed:
    min: 1
    max: 3000000000
EarlyStopping:
  patience: 5
  min_delta: 0
  decreasing: False