program: run_train.py
name: swipe-seed-churn
project: Random_seed_churn
method: random #bayes grid
run_cap: 1000
metric:
  name: val_acc
  goal: maximize
model: nn.Sequential(
            nn.Linear(input_size, hidden_sizes[0]),
            nn.ReLU(),
            nn.Linear(hidden_sizes[0], hidden_sizes[1]),
            nn.ReLU(),
            nn.Linear(hidden_sizes[1], output_size),
            nn.Sigmoid(),
        )
parameters:
  epochs: 
    value: 90
  batch_size: 
    values: [256]
  lr:
    values: [0.01]
  dataset:
    value: 'ibm_attrition'
  seed:
    min: 1
    max: 3000000000
EarlyStopping:
  patience: 5
  min_delta: 0
  decreasing: False