program: run_train.py
name: swipe-seed-cancer
project: Random_seed_cancer
method: random
run_cap: 1000
metric:
  name: val_acc
  goal: maximize
parameters:
  epochs: 
    value: 90
  batch_size: 
    values: [128]
  lr:
    values: [0.01]
  dataset:
    value: 'cancer_risk'
  seed:
    min: 1
    max: 3000000000
EarlyStopping:
  patience: 5
  min_delta: 0
  decreasing: False