program: run_train.py
name: swipe-seed-churn-bs
project: Random_seed_churn_bs
method: random
run_cap: 1000
metric:
  name: val_acc
  goal: maximize
parameters:
  epochs: 
    value: 90
  batch_size: 
    values: [998]
  lr:
    values: [0.01]
  lr_decay:
    value: False
  dataset:
    value: 'churn_dataset'
  seed:
    min: 1
    max: 3000000000
EarlyStopping:
  patience: 5
  min_delta: 0
  decreasing: False