program: run_train.py
name: swipe-models
project: model-definition-1
method: random #bayes grid
run_cap: 4
metric:
  name: val_acc
  goal: maximize
# model: nn.Sequential(
#             nn.Linear(input_size, hidden_sizes[0]),
#             nn.ReLU(),
#             nn.Linear(hidden_sizes[0], hidden_sizes[1]),
#             nn.ReLU(),
#             nn.Linear(hidden_sizes[1], output_size),
#             nn.Sigmoid(),
#         )

parameters:
  epochs: 
    value: 70
  batch_size: 
    values: 
      #- 32
      #- 64
      #- 128
      - 256
      - 512
  lr:
    values: [0.01]
  dataset:
    value: 'adult_dataset'
  seed:
    value: 42
  model: 
    value: nn.Sequential(
           nn.Linear(input_size, 128),
           nn.ReLU(),
           nn.Dropout(0.5),
           nn.Linear(128, 64),
           nn.ReLU(),
           nn.Dropout(0.5),
           nn.Linear(64, 32),
           nn.ReLU(),
           nn.Dropout(0.5),
           nn.Linear(32, output_size),
           nn.Sigmoid()
        )
EarlyStopping:
  patience: 5
  min_delta: 0
  decreasing: False
