program: run_train.py
name: swipe-yaml
project: sweep-wnadb-debug_4
method: random #bayes grid
run_cap: 1
metric:
  name: val_acc
  goal: maximize
model: nn.Sequential(
            nn.Linear(input_size, hidden_sizes[0]),
            nn.ReLU(),
            nn.Linear(hidden_sizes[0], hidden_sizes[1]),
            nn.ReLU(),
            nn.Linear(hidden_sizes[1], output_size),
            nn.Sigmoid(),
        )
parameters:
  epochs: 
    value: 2
  batch_size: 
    values: 
      - 16 
      - 32
      - 64
  lr:
    value: 0.1
