program: run_train.py
name: 'swipe-yaml'
project: sweep-wnadb-debug_4
method: random #bayes grid
run_cap: 3
metric:
  name: val_acc
  goal: maximize
parameters:
  epochs: 
    value: 2
  batch_size: 
    values: 
      - 16 
      - 32
      - 64
  lr:
    value: 0.1
