wandb_version: 1

batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 2
lr:
  desc: null
  value: 0.01915674558405971
_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.15.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689422794.012978
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 17
      - 23
      - 37
      4: 3.7.16
      5: 0.15.3
      8:
      - 5
